on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Doxygen
      run: |
        sudo apt -y install doxygen
    - name: Generate Doxygen documentation
      run: |
        doxygen
    - name: Save documentation as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: html/
